// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Registry struct {
	ID               pgtype.UUID
	RegistrationID   string
	Isbn             pgtype.Text
	Title            string
	Author           pgtype.Text
	Translator       pgtype.Text
	PrintAmount      pgtype.Int4
	SelfPublish      pgtype.Bool
	Partner          pgtype.Text
	RegistrationDate pgtype.Date
}
