// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistry = `-- name: CreateRegistry :one
INSERT INTO registry (
    registration_id, isbn, title, author, translator, print_amount, self_publish, partner, registration_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, registration_id, isbn, title, author, translator, print_amount, self_publish, partner, registration_date
`

type CreateRegistryParams struct {
	RegistrationID   string
	Isbn             pgtype.Text
	Title            string
	Author           pgtype.Text
	Translator       pgtype.Text
	PrintAmount      pgtype.Int4
	SelfPublish      pgtype.Bool
	Partner          pgtype.Text
	RegistrationDate pgtype.Date
}

func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, createRegistry,
		arg.RegistrationID,
		arg.Isbn,
		arg.Title,
		arg.Author,
		arg.Translator,
		arg.PrintAmount,
		arg.SelfPublish,
		arg.Partner,
		arg.RegistrationDate,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Translator,
		&i.PrintAmount,
		&i.SelfPublish,
		&i.Partner,
		&i.RegistrationDate,
	)
	return i, err
}

const getRegistryByRegistrationID = `-- name: GetRegistryByRegistrationID :one
SELECT id, registration_id, isbn, title, author, translator, print_amount, self_publish, partner, registration_date FROM registry
WHERE registration_id = $1 LIMIT 1
`

func (q *Queries) GetRegistryByRegistrationID(ctx context.Context, registrationID string) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistryByRegistrationID, registrationID)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Translator,
		&i.PrintAmount,
		&i.SelfPublish,
		&i.Partner,
		&i.RegistrationDate,
	)
	return i, err
}

const listRegistry = `-- name: ListRegistry :many
SELECT id, registration_id, isbn, title, author, translator, print_amount, self_publish, partner, registration_date FROM registry
LIMIT $1 OFFSET $2
`

type ListRegistryParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRegistry(ctx context.Context, arg ListRegistryParams) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistry, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registry
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Translator,
			&i.PrintAmount,
			&i.SelfPublish,
			&i.Partner,
			&i.RegistrationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
